version: "3.8"

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000-8002:8000"
    deploy:
      replicas: 1
    environment:
      - PYTHONUNBUFFERED=1